version: '3.5'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    command : npm start
    ports:
      - 3000:3000
    links:
      - mongodb  
    depends_on: 
      - mongodb
    tty: true
  mongodb:
    image: mongo:latest
